# Generated by Django 5.2.4 on 2025-07-30 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='todos',
            new_name='Todo',
        ),
    ]
